// WARNING: Please don't edit this file. It was generated by C++/WinRT v2.0.220929.3

#pragma once
#ifndef WINRT_Volcanobet_WINGO_1_H
#define WINRT_Volcanobet_WINGO_1_H
#include "winrt/impl/Volcanobet_WINGO.0.h"
WINRT_EXPORT namespace winrt::Volcanobet_WINGO
{
    struct __declspec(empty_bases) IMainWindow :
        winrt::Windows::Foundation::IInspectable,
        impl::consume_t<IMainWindow>
    {
        IMainWindow(std::nullptr_t = nullptr) noexcept {}
        IMainWindow(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
}
#endif
