// WARNING: Please don't edit this file. It was generated by C++/WinRT v2.0.220929.3

#pragma once
#ifndef WINRT_Volcanobet_WINGO_0_H
#define WINRT_Volcanobet_WINGO_0_H
WINRT_EXPORT namespace winrt::Microsoft::UI::Xaml::Markup
{
    struct IXamlMetadataProvider;
}
WINRT_EXPORT namespace winrt::Volcanobet_WINGO
{
    struct IMainWindow;
    struct MainWindow;
    struct XamlMetaDataProvider;
}
namespace winrt::impl
{
    template <> struct category<winrt::Volcanobet_WINGO::IMainWindow>{ using type = interface_category; };
    template <> struct category<winrt::Volcanobet_WINGO::MainWindow>{ using type = class_category; };
    template <> struct category<winrt::Volcanobet_WINGO::XamlMetaDataProvider>{ using type = class_category; };
    template <> inline constexpr auto& name_v<winrt::Volcanobet_WINGO::MainWindow> = L"Volcanobet_WINGO.MainWindow";
    template <> inline constexpr auto& name_v<winrt::Volcanobet_WINGO::XamlMetaDataProvider> = L"Volcanobet_WINGO.XamlMetaDataProvider";
    template <> inline constexpr auto& name_v<winrt::Volcanobet_WINGO::IMainWindow> = L"Volcanobet_WINGO.IMainWindow";
    template <> inline constexpr guid guid_v<winrt::Volcanobet_WINGO::IMainWindow>{ 0x2DAD0211,0xFB1D,0x5E9B,{ 0x92,0xA2,0x9C,0x2B,0x5C,0x4F,0xE1,0x49 } }; // 2DAD0211-FB1D-5E9B-92A2-9C2B5C4FE149
    template <> struct default_interface<winrt::Volcanobet_WINGO::MainWindow>{ using type = winrt::Volcanobet_WINGO::IMainWindow; };
    template <> struct default_interface<winrt::Volcanobet_WINGO::XamlMetaDataProvider>{ using type = winrt::Microsoft::UI::Xaml::Markup::IXamlMetadataProvider; };
    template <> struct abi<winrt::Volcanobet_WINGO::IMainWindow>
    {
        struct __declspec(novtable) type : inspectable_abi
        {
            virtual int32_t __stdcall get_MyProperty(int32_t*) noexcept = 0;
            virtual int32_t __stdcall put_MyProperty(int32_t) noexcept = 0;
        };
    };
    template <typename D>
    struct consume_Volcanobet_WINGO_IMainWindow
    {
        [[nodiscard]] auto MyProperty() const;
        auto MyProperty(int32_t value) const;
    };
    template <> struct consume<winrt::Volcanobet_WINGO::IMainWindow>
    {
        template <typename D> using type = consume_Volcanobet_WINGO_IMainWindow<D>;
    };
}
#endif
