// WARNING: Please don't edit this file. It was generated by C++/WinRT v2.0.220929.3

void* winrt_make_Volcanobet_WINGO_MainWindow()
{
    return winrt::detach_abi(winrt::make<winrt::Volcanobet_WINGO::factory_implementation::MainWindow>());
}
WINRT_EXPORT namespace winrt::Volcanobet_WINGO
{
    MainWindow::MainWindow() :
        MainWindow(make<Volcanobet_WINGO::implementation::MainWindow>())
    {
    }
}
