// WARNING: Please don't edit this file. It was generated by C++/WinRT v2.0.220929.3

void* winrt_make_Volcanobet_WINGO_XamlMetaDataProvider()
{
    return winrt::detach_abi(winrt::make<winrt::Volcanobet_WINGO::factory_implementation::XamlMetaDataProvider>());
}
WINRT_EXPORT namespace winrt::Volcanobet_WINGO
{
    XamlMetaDataProvider::XamlMetaDataProvider() :
        XamlMetaDataProvider(make<Volcanobet_WINGO::implementation::XamlMetaDataProvider>())
    {
    }
}
