// WARNING: Please don't edit this file. It was generated by C++/WinRT v2.0.220929.3

void* winrt_make_DesktopAPP_MainWindow()
{
    return winrt::detach_abi(winrt::make<winrt::DesktopAPP::factory_implementation::MainWindow>());
}
WINRT_EXPORT namespace winrt::DesktopAPP
{
    MainWindow::MainWindow() :
        MainWindow(make<DesktopAPP::implementation::MainWindow>())
    {
    }
}
