// WARNING: Please don't edit this file. It was generated by C++/WinRT v2.0.220929.3

void* winrt_make_DesktopAPP_XamlMetaDataProvider()
{
    return winrt::detach_abi(winrt::make<winrt::DesktopAPP::factory_implementation::XamlMetaDataProvider>());
}
WINRT_EXPORT namespace winrt::DesktopAPP
{
    XamlMetaDataProvider::XamlMetaDataProvider() :
        XamlMetaDataProvider(make<DesktopAPP::implementation::XamlMetaDataProvider>())
    {
    }
}
