// WARNING: Please don't edit this file. It was generated by C++/WinRT v2.0.220929.3

#pragma once
#ifndef WINRT_DesktopAPP_0_H
#define WINRT_DesktopAPP_0_H
WINRT_EXPORT namespace winrt::Microsoft::UI::Xaml::Markup
{
    struct IXamlMetadataProvider;
}
WINRT_EXPORT namespace winrt::DesktopAPP
{
    struct IMainWindow;
    struct MainWindow;
    struct XamlMetaDataProvider;
}
namespace winrt::impl
{
    template <> struct category<winrt::DesktopAPP::IMainWindow>{ using type = interface_category; };
    template <> struct category<winrt::DesktopAPP::MainWindow>{ using type = class_category; };
    template <> struct category<winrt::DesktopAPP::XamlMetaDataProvider>{ using type = class_category; };
    template <> inline constexpr auto& name_v<winrt::DesktopAPP::MainWindow> = L"DesktopAPP.MainWindow";
    template <> inline constexpr auto& name_v<winrt::DesktopAPP::XamlMetaDataProvider> = L"DesktopAPP.XamlMetaDataProvider";
    template <> inline constexpr auto& name_v<winrt::DesktopAPP::IMainWindow> = L"DesktopAPP.IMainWindow";
    template <> inline constexpr guid guid_v<winrt::DesktopAPP::IMainWindow>{ 0xD2FBAF7D,0x4F67,0x51BC,{ 0xB1,0x4F,0x97,0x22,0x0E,0xE5,0x24,0x05 } }; // D2FBAF7D-4F67-51BC-B14F-97220EE52405
    template <> struct default_interface<winrt::DesktopAPP::MainWindow>{ using type = winrt::DesktopAPP::IMainWindow; };
    template <> struct default_interface<winrt::DesktopAPP::XamlMetaDataProvider>{ using type = winrt::Microsoft::UI::Xaml::Markup::IXamlMetadataProvider; };
    template <> struct abi<winrt::DesktopAPP::IMainWindow>
    {
        struct __declspec(novtable) type : inspectable_abi
        {
            virtual int32_t __stdcall get_MyProperty(int32_t*) noexcept = 0;
            virtual int32_t __stdcall put_MyProperty(int32_t) noexcept = 0;
        };
    };
    template <typename D>
    struct consume_DesktopAPP_IMainWindow
    {
        [[nodiscard]] auto MyProperty() const;
        auto MyProperty(int32_t value) const;
    };
    template <> struct consume<winrt::DesktopAPP::IMainWindow>
    {
        template <typename D> using type = consume_DesktopAPP_IMainWindow<D>;
    };
}
#endif
